language: node_js
branches:
  only:
    - master
    - development

# bcrypt with node 4.x
env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

node_js:
   - "4"

matrix:
  fast_finish: true
services:
  - redis-server

# container-base
sudo: false
