language: node_js
branches:
  only:
    - master
    - development
node_js:
   - "iojs"
   - "iojs-v2.5.0"
   - "0.12"
   - "4.0"
matrix:
  fast_finish: true
  allow_failures:
    - node_js: "iojs"
    - node_js: "4.0"
